---
openapi: 3.0.0
info:
  title: Rewards
  description: uChoose Rewards API. This API provides functionality to clients for searching, viewing, consuming uChoose Offers and Points.
  version: 1.0.0
servers:
- url: https://card.api.fiservapps.com/cs/rewards
  description: Production url
- url: https://card-certification.api.fiservapps.com/cs/rewards
  description: Certification url
- url: https://card-sandbox.api.fiservapps.com/cs/rewards
  description: Sandbox url
security:
- BearerAuth: []
tags:
- name: View Offer
  description: Provides ability to search and activate in-store offers for loyalty members.
paths:
  /v1/offers/search:
    post:
      tags:
      - View Offer
      x-child-product-name: Rewards v1.0.0
      x-group-name: View Offer
      x-proxy-name: Search Offers
      summary: Retrieve uChoose reward offers for loyalty members based on various search criteria.
      description: Search uChoose reward offers for loyalty members. This API allows searching featured offers which are based on personal shopping behaviour, preferences and rules specific to the client's program. Also it allows searching for non-targetted offers based on different search criteria.
      operationId: searchOffers
      parameters:
      - name: filter
        in: query
        description: 'Optional. Restricts search to targeted offers for loyalty members when used.  Targeted offers are a specially selected subset of all available offers. '
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: featuredOffers
      - name: Authorization
        in: header
        description: 'Retrieve an access token through the Access Token API. Access token is required in every request. Refer to documentation on access token  (https://card.developer.fiserv.com/apis/token).Tokens expire after 15 minutes. Provide the value as follows in the header. Authorization: Bearer <Access Token Value>'
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: Bearer USlfM8dilzKZPcuGGP3BfVLd7Snk
      - name: userId
        in: header
        description: User who is making this request. This is optional, if passed will be used for granular level auditing.
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: FDSCARD
      - name: x-fapi-financial-id
        in: header
        description: Required. Provide 8 digit integer client id
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "12345678"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfferSearchRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferSearchResponse'
        "400":
          description: Invalid Request
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400Error'
        "401":
          description: Unauthorized access
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401Error'
        "403":
          description: Forbidden
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403Error'
        "404":
          description: Not Found
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'
        "405":
          description: Method Not Allowed
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
        "406":
          description: Unacceptable
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
        "409":
          description: Resource conflict
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/409Error'
        "415":
          description: Unsupported Media Type
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/415Error'
        "422":
          description: Unprocessable Entity
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
        "429":
          description: Too Many Requests
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
        "500":
          description: Internal Server Error
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                type: object
                example:
                  errorResponse:
                    code: 500-01
                    message: internal server error
                    developerInfo:
                      developerMessage: internal server error
                      moreInfo: There was a problem handling your request.  Please try again.  If the problem persists please contact Fiserv ETSD at 888-243-2543 (unique messageID included below)
                      messageid: 25557-84290371-1
  /v1/offers/activation:
    patch:
      tags:
      - View Offer
      x-child-product-name: Rewards v1.0.0
      x-group-name: View Offer
      x-proxy-name: Offer Activation
      summary: Activate an offer, makes a loyalty member eligible to receive the rewards provided by the requested offer.
      operationId: offerActivation
      parameters:
      - name: Authorization
        in: header
        description: 'Retrieve an access token through the Access Token API. Access token is required in every request. Refer to documentation on access token  (https://card.developer.fiserv.com/apis/token).Tokens expire after 15 minutes. Provide the value as follows in the header. Authorization: Bearer <Access Token Value>'
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: Bearer USlfM8dilzKZPcuGGP3BfVLd7Snk
      - name: userId
        in: header
        description: User who is making this request. This is optional, if passed will be used for granular level auditing.
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: FDSCARD
      - name: x-fapi-financial-id
        in: header
        description: Required. Provide 8 digit integer client id
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "12345678"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivateOfferRequest'
      responses:
        "204":
          description: Successful
        "400":
          description: Invalid Request
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400Error'
        "401":
          description: Unauthorized access
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401Error'
        "403":
          description: Forbidden
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403Error'
        "404":
          description: Not Found
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'
        "405":
          description: Method Not Allowed
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
        "406":
          description: Unacceptable
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
        "409":
          description: Resource conflict
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/409Error'
        "415":
          description: Unsupported Media Type
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/415Error'
        "422":
          description: Unprocessable Entity
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
        "429":
          description: Too Many Requests
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
        "500":
          description: Internal Server Error
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                type: object
                example:
                  errorResponse:
                    code: 500-01
                    message: internal server error
                    developerInfo:
                      developerMessage: internal server error
                      moreInfo: There was a problem handling your request.  Please try again.  If the problem persists please contact Fiserv ETSD at 888-243-2543 (unique messageID included below)
                      messageid: 25557-84290371-1
  /v1/offers/{offerId}:
    post:
      tags:
      - View Offer
      x-child-product-name: Rewards v1.0.0
      x-group-name: View Offer
      x-proxy-name: Offer Detail
      summary: Retrieve the details of a specific offer based on its unique ID.
      operationId: offerDetail
      parameters:
      - name: Authorization
        in: header
        description: 'Retrieve an access token through the Access Token API. Access token is required in every request. Refer to documentation on access token  (https://card.developer.fiserv.com/apis/token).Tokens expire after 15 minutes. Provide the value as follows in the header. Authorization: Bearer <Access Token Value>'
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: Bearer USlfM8dilzKZPcuGGP3BfVLd7Snk
      - name: userId
        in: header
        description: User who is making this request. This is optional, if passed will be used for granular level auditing.
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: FDSCARD
      - name: x-fapi-financial-id
        in: header
        description: Required. Provide 8 digit integer client id
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: "12345678"
      - name: offerId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          description: Numeric ID of the user to get
          example: "103557"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfferDetailRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferDetailResponse'
        "400":
          description: Invalid Request
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400Error'
        "401":
          description: Unauthorized access
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401Error'
        "403":
          description: Forbidden
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403Error'
        "404":
          description: Not Found
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'
        "405":
          description: Method Not Allowed
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
        "406":
          description: Unacceptable
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
        "415":
          description: Unsupported Media Type
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/415Error'
        "422":
          description: Unprocessable Entity
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
        "429":
          description: Too Many Requests
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
        "500":
          description: Internal Server Error
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/interactionId'
          content:
            application/json:
              schema:
                type: object
                example:
                  errorResponse:
                    code: 500-01
                    message: internal server error
                    developerInfo:
                      developerMessage: internal server error
                      moreInfo: There was a problem handling your request.  Please try again.  If the problem persists please contact Fiserv ETSD at 888-243-2543 (unique messageID included below)
                      messageid: 25557-84290371-1
components:
  schemas:
    "400Error":
      type: object
      properties:
        type:
          type: string
          description: An URI reference that identifies the problem type
          example: Input Validation Exception
        title:
          type: string
          description: Short summary of the problem.
          example: Bad Request
        detail:
          type: string
          description: Specific explanation to the occurence of the problem.
          example: CONTENT-TYPE header required. Supported content-type is application/json
        instance:
          type: string
          description: A URI reference that identifies the specific occurence of the problem.
          example: /api/basepath
        status:
          type: number
          description: The HTTP status code generated by the origin server for this occurance of the problem.
          example: 400
    "401Error":
      type: object
      properties:
        type:
          type: string
          description: An URI reference that identifies the problem type
          example: https://card.developer.fiserv.com/cards/error#unauthorized
        title:
          type: string
          description: Short summary of the problem.
          example: Unauthorized
        detail:
          type: string
          description: Specific explanation to the occurence of the problem.
          example: Invalid Access Token.
        instance:
          type: string
          description: A URI reference that identifies the specific occurence of the problem.
          example: /api/basepath
        status:
          type: number
          description: The HTTP status code generated by the origin server for this occurance of the problem.
          example: 401
    "403Error":
      type: object
      properties:
        type:
          type: string
          description: An URI reference that identifies the problem type
          example: https://card.developer.fiserv.com/cards/error#forbidden
        title:
          type: string
          description: Short summary of the problem.
          example: Forbidden
        detail:
          type: string
          description: Specific explanation to the occurence of the problem.
          example: Authorization failure.
        instance:
          type: string
          description: A URI reference that identifies the specific occurence of the problem.
          example: /api/basepath
        status:
          type: number
          description: The HTTP status code generated by the origin server for this occurance of the problem.
          example: 403
    "404Error":
      type: object
      properties:
        type:
          type: string
          description: An URI reference that identifies the problem type
          example: Resource does not exists
        title:
          type: string
          description: Short summary of the problem.
          example: offer Not Found or expired
        detail:
          type: string
          description: Specific explanation to the occurence of the problem.
          example: No matching search results found or you do not have sufficient access rights to get search results matching your criteria.
        instance:
          type: string
          description: A URI reference that identifies the specific occurence of the problem.
          example: /api/basepath
        status:
          type: number
          description: The HTTP status code generated by the origin server for this occurance of the problem.
          example: 404
    "409Error":
      type: object
      properties:
        type:
          type: string
          description: An URI reference that identifies the problem type
          example: Http Resource conflict error
        title:
          type: string
          description: Short summary of the problem.
          example: Resource conflict
        detail:
          type: string
          description: Specific explanation to the occurence of the problem.
          example: Could not active offer. Offer is already activated.
        instance:
          type: string
          description: A URI reference that identifies the specific occurence of the problem.
          example: /api/basepath
        status:
          type: number
          description: The HTTP status code generated by the origin server for this occurance of the problem.
          example: 409
    "415Error":
      type: object
      properties:
        type:
          type: string
          description: An URI reference that identifies the problem type
          example: https://card.developer.fiserv.com/cards/error#unsupported-mediatype
        title:
          type: string
          description: Short summary of the problem.
          example: Unsupported Media Type
        detail:
          type: string
          description: Specific explanation to the occurence of the problem.
          example: Unsupported Media Type.
        instance:
          type: string
          description: A URI reference that identifies the specific occurence of the problem.
          example: /api/basepath
        status:
          type: number
          description: The HTTP status code generated by the origin server for this occurance of the problem.
          example: 415
    ActivateOfferRequest:
      required:
      - offerId
      type: object
      properties:
        cardNumber:
          maxLength: 19
          minLength: 16
          type: string
          description: Card number of primary cardholder.
          format: numeric
          example: "4000200030004000"
        accountNumber:
          type: string
          description: Account identifier of the cardholder.
          example: "123456789"
        offerId:
          type: string
          description: The unique offer identifier that is retrieved from offerSearch.
          example: "103557"
    Category:
      type: object
      properties:
        categoryId:
          type: string
          description: The offer category unique identifier.
          example: "38460"
        categoryDescription:
          type: string
          description: The description of the category.
          example: Kids & Toys
    OfferSearchRequest:
      required:
      - cardNumber
      type: object
      properties:
        cardNumber:
          maxLength: 19
          minLength: 16
          type: string
          description: Card number of primary cardholder.
          format: numeric
          example: "4000200030004000"
        accountNumber:
          type: string
          description: Account identifier of the cardholder.
          example: "123456789"
        offerId:
          type: string
          description: Unique offer identifier.
          example: "103557"
        merchantPartnerName:
          type: string
          description: The keyword used to match with the partial or full merchant partner name.
          example: The 1St Lady Boutique OR Boutique
        shopType:
          type: string
          description: Shopping type for offer.
          example: IN_STORE
          default: IN_STORE
          enum:
          - ONLINE
          - IN_STORE
          - BOTH
        searchScope:
          type: string
          description: Locale of the offer.
          example: LOCAL
          default: LOCAL
          enum:
          - NATIONAL
          - LOCAL
          - ONLINE
        requiresActivation:
          type: boolean
          description: Include or exclude offers requiring activation.
          example: false
          default: false
        activated:
          type: boolean
          description: Include or exclude offers the current loyalty member has activated. Only applies to offers that need activation..
          example: true
          default: false
        categoryId:
          type: string
          description: Unique identifier for offer category.
          example: "38460"
        partnerId:
          type: string
          description: Unique identifier of merchant partner owning the offer.
          example: "39203"
        keyword:
          type: string
          description: The search keyword associated with offers.
          example: shoe
        letter:
          maxLength: 1
          type: string
          description: The first alphanumeric character of the offer name. Helps with alphanumeric pagination filtering.
          example: S
        startRange:
          type: string
          description: The lowest value of offers retrieved.  Part of a range.
          example: "3"
        endRange:
          type: string
          description: The highest value of offers retrieved.  Part of a range.
          example: "5"
        fundingCategory:
          type: string
          description: The campaign funding category for the offers.
          example: FEATURED
          default: NONE
          enum:
          - NONE
          - FEATURED
          - SELECT
          - SPOTLIGHT
        radius:
          type: integer
          description: Radius value in miles within which in-store offers included in result.
          example: 50
          default: 25
        zipCode:
          type: string
          description: Zip code of in-store offers.
          example: "38018"
        city:
          type: string
          description: City for which the in-store offers are available.
          example: Cordova
        state:
          type: string
          description: State for which the in-store offers are available.
          example: TN
        latitude:
          type: number
          description: Latitude value for which the in-store offers are available.
          example: 35.144207
        longtitude:
          type: number
          description: Longtitude value for which the in-store offers are available
          example: -89.795442
        storesPerPage:
          type: string
          description: Stores per page to be returned.
          example: "999"
        storePageCount:
          type: string
          description: The specific API stores list page carrying the number of store records specified under storesPerPage. Page numbers are calculated per the given storesPerPage value and total number of available stores for the offer
          example: "5"
          default: "1000"
        sortOrder:
          type: string
          description: The sorting direction.
          example: ASC
          default: DESC
          enum:
          - ASC
          - DESC
        sort:
          type: string
          description: Fields on which offer response can be sorted. The sort can be done only one at a time.
          example: NONE
          default: NONE
          enum:
          - NONE
          - RANK
          - MERCHANT_PARTNER_NAME
          - OFFER
          - SHOP_TYPE
          - OFFER_EXPIRATION_DATE
          - DATE_CREATED
          - CAMPAIGN_START_TIME
          - SPEND
          - CLICK_TREND
        geoFilter:
          type: boolean
          description: If true (default), filter by geo (physical location).
          example: true
          default: true
        matchType:
          type: string
          description: If set to multi_match, filters for offers with exact matches of the search keyword provided under filters merchantPartnerName or keywords. If not set, filters for offers with partial matches of the search keyword provided under filters merchantPartnerName or keyword.
          example: SINGLE_MATCH
          enum:
          - MULTI_MATCH
          - SINGLE_MATCH
        offerRecordsPerPage:
          type: string
          description: The number of offers to be returned per request.
          example: "15"
          default: "25"
        pageCount:
          type: string
          description: Page count per request.
          example: "1"
          default: "1"
    OfferSearchResponse:
      type: object
      properties:
        offerSearchParameters:
          $ref: '#/components/schemas/OfferSearchResponse_offerSearchParameters'
    OfferDetailRequest:
      required:
      - accountNumber
      - cardNumber
      type: object
      properties:
        cardNumber:
          maxLength: 19
          minLength: 16
          type: string
          description: Card number of primary cardholder.
          format: numeric
          example: "4000200030004000"
        accountNumber:
          type: string
          description: Account identifier of the cardholder.
          example: "123456789"
    OfferDetailResponse:
      type: object
      properties:
        offerId:
          type: string
          description: The offer's unique ID for which the details are requested.
          example: "103557"
        offerValue:
          type: string
          description: Numeric value of the offer.
          example: "5"
        offerValueDescription:
          type: string
          description: A short description of the offer value. Usually empty if merchant offer is populated.
          example: 2%
        offerTermsAndConditions:
          type: string
          description: The offer terms and conditions.
          example: Offer expires 2015-06-30.
        offerExpirationDate:
          type: string
          description: The offer expiration date in UTC format.
          example: "20200923"
        categories:
          type: array
          description: The list of categories that apply to the current offer.
          items:
            $ref: '#/components/schemas/Category'
        shopType:
          type: array
          items:
            type: string
            description: Shopping type for offer.
            example: IN_STORE
            default: IN_STORE
            enum:
            - ONLINE
            - IN_STORE
            - BOTH
        merchantPartnerName:
          type: string
          description: The keyword used to match with the partial or full merchant partner name.
          example: The 1St Lady Boutique OR Boutique
        merchantOfferDescription:
          type: string
          description: A short description of the offer value.
          example: Earn 5 Points per $1 at 1000 Degrees Neapolitan Pizza.
        merchantNameOfferDescription:
          type: string
          description: A friendly version of the merchant offer description that includes the merchant name.
          example: Earn 5 Points per dollar at Rock Me Makeup on purchases of $50 or more.
        merchantOfferExternalUrl:
          type: string
          description: The offer URL on the merchant's website.
          example: ""
        merchantLogoFileNameUrl:
          type: string
          description: The merchant logo filename1Url.
          example: https://uchooserewards.com/data/images/lego_90x50_4.2.08.gif
        activated:
          type: boolean
          description: Indicates if the current loyalty member has activated the offer.
          example: true
          default: false
        requiresActivation:
          type: boolean
          description: Indicates if the offer requires activation.
          example: false
          default: false
        partnerId:
          type: string
          description: Unique identifier of merchant partner owning offer.
          example: "24966"
        shortMerchantOffer:
          type: string
          description: The merchant offer amount. This is the shortest offer text version that should go with the merchant logo on the offers list view.
          example: 5 Points per dollar
        locationCount:
          type: string
          description: Number of in-store locations where the offer is available.
          example: "10"
        alphaIndex:
          type: string
          description: The first character of the merchant name.
          example: r
        spend:
          type: string
          description: The average dollar amount spend for the merchant offer during the last month. Offers with higher spend values are deemed trending or most popular.
          example: ""
        clickTrend:
          type: string
          description: The average click rate for the merchant offer during the last three months. Offers with higher click trends could be deemed trending or most popular.
          example: ""
        fundingCategory:
          type: string
          description: The campaign funding category for the offers.
          example: FEATURED
          default: NONE
          enum:
          - NONE
          - FEATURED
          - SELECT
          - SPOTLIGHT
        bonusEarned:
          type: string
          description: Denotes whether the loyaly member has earned the bonus on the offer or not.
          example: "false"
        stores:
          type: array
          items:
            $ref: '#/components/schemas/Stores'
    Offers:
      type: object
      properties:
        offerId:
          type: string
          description: The unique offer identifier that is retrieved from offerSearch.
          example: "103557"
        merchantPartnerName:
          type: string
          description: The merchant partner name in the content management system.
          example: LEGO
        merchantLogoFileNameUrl:
          type: string
          description: The merchant logo filename URL.
          example: https://uchooserewards.com/data/images/lego_90x50_4.2.08.gif
        merchantPartnerId:
          type: string
          description: The unique merchant partner ID.
        offerTermsAndConditions:
          type: string
          description: The offer terms and conditions.
          example: 'Offer expires 2015-03-31.'
        merchantOfferExternalUrl:
          type: string
          description: The offer URL on the merchant's website.
          example: http://click.linksynergy.com/fs-bin/click?id=E7Il34ja9WM&offerid=115554.10000195&type=3&subid=0&u1=26XXdKrlo26
        offerValueDescription:
          type: string
          description: A short description of the offer value. Usually empty if offerDescription is populated.
          example: ""
        categories:
          type: array
          description: The list of categories to which the current offer is related.
          items:
            $ref: '#/components/schemas/Category'
        offerExpirationDate:
          type: string
          description: The offer expiration date in UTC format.
          example: "20220923"
        requiresActivation:
          type: boolean
          description: Indicates if offers requires activation from member.
          example: false
          default: false
        offerValue:
          type: string
          description: Numeric value of the offer.
          example: "2"
        activated:
          type: boolean
          description: Indicates if the current loyalty member has activated the offer.
          example: true
          default: false
        shopType:
          type: array
          items:
            type: string
            description: Shopping type for offer.
            example: IN_STORE
            default: IN_STORE
            enum:
            - ONLINE
            - IN_STORE
            - BOTH
        offerDescription:
          type: string
          description: A short description of the offer value.
          example: Earn 2% Cash back at LEGO.
        shortMerchantOffer:
          type: string
          description: The merchant offer amount. This is the shortest offer text version that should go with the merchant logo on the offers list view.
          example: 2% Cash back
        merchantOfferDescription:
          type: string
          description: A friendly version of the merchant offer description that includes the merchant name.
          example: Earn 2% Cash back at LEGO.
        locationCount:
          type: string
          description: Number of in-store locations where the offer is available.
          example: "10"
        partnerId:
          type: string
          description: Unique identifier of merchant partner owning offer.
          example: "2537"
        alphaIndex:
          type: string
          description: The first character of the merchant name.
          example: l
        spend:
          type: string
          description: The average dollar amount spend for the merchant offer during the last month. Offers with higher spend values are deemed trending or most popular.
          example: ""
        clickTrend:
          type: string
          description: The average click rate for the merchant offer during the last three months. Offers with higher click trends could be deemed trending or most popular.
          example: ""
        fundingCategory:
          type: string
          description: The campaign funding category that applies to the offers.
          example: FEATURED
          default: NONE
          enum:
          - NONE
          - FEATURED
          - SELECT
          - SPOTLIGHT
        bonusEarned:
          type: boolean
          description: Indicates if the loyaly member has earned the bonus on the offer.
          example: false
        stores:
          type: array
          items:
            $ref: '#/components/schemas/Stores'
    Stores:
      type: object
      properties:
        storesId:
          type: string
          description: The unique store identifier.
          example: "232232"
        name:
          type: string
          description: Name of the store.
          example: Bed Bath & Beyond
        locationName:
          type: string
          description: Location of the store.
          example: Mira Loma
        address:
          type: string
          description: Address of the store.
          example: 6365 Pats Ranch Road
        city:
          type: string
          description: City in which the store is located.
          example: Mira Loma
        state:
          type: string
          description: The state details of the store.
          example: CA
        zip:
          type: string
          description: The zipcode of the store.
          example: "91752"
        longtitude:
          type: string
          description: Longtitude in which the store is located.
          example: "-117.54465999999999"
        latitude:
          type: string
          description: Latitude in which the store is located.
          example: "33.972551000000003"
        phone:
          type: string
          description: Phone number of the store.
          example: "7568142562"
        venueId:
          type: string
          description: Unique venue identifier.
          example: ""
        notes:
          type: string
          example: Next to shoprite.
        distance:
          type: string
          example: "0.0"
    OfferSearchResponse_offerSearchParameters:
      type: object
      properties:
        radius:
          type: integer
          description: Radius value in miles within which in-store offers to be searched.
          example: 50
          default: 25
        offerRecordsPerPage:
          type: string
          description: The number of offers to be returned per single API call.
          example: "15"
          default: "25"
        totalPages:
          type: string
          description: The number of pages to be returned per single API call
          example: "10"
        pageCount:
          type: string
          description: Page count per offer API response.
          example: "1"
          default: "1"
        groupBy:
          type: string
          description: The number of offer records returned per a single API call. Useful for pagination purposes.
          example: "1"
          default: "25"
        sort:
          type: string
          description: Fields on which offer response can be sorted.The sort can be done only one at a time.
          example: NONE
          default: NONE
          enum:
          - NONE
          - RANK
          - MERCHANT_PARTNER_NAME
          - OFFER
          - SHOP_TYPE
          - OFFER_EXPIRATION_DATE
          - DATE_CREATED
          - CAMPAIGN_START_TIME
          - SPEND
          - CLICK_TREND
        sortOrder:
          type: string
          description: The sorting direction.
          example: ASC
          default: DESC
          enum:
          - ASC
          - DESC
        geoFilter:
          type: boolean
          description: Indicates if geo filtering (physical location) applied.
          example: true
          default: true
        offers:
          type: array
          items:
            $ref: '#/components/schemas/Offers'
  parameters:
    userIdParam:
      name: userId
      in: header
      description: User who is making this request. This is optional, if passed will be used for granular level auditing.
      required: false
      style: simple
      explode: false
      schema:
        type: string
      example: FDSCARD
    authorizationParam:
      name: Authorization
      in: header
      description: 'Retrieve an access token through the Access Token API. Access token is required in every request. Refer to documentation on access token  (https://card.developer.fiserv.com/apis/token).Tokens expire after 15 minutes. Provide the value as follows in the header. Authorization: Bearer <Access Token Value>'
      required: true
      style: simple
      explode: false
      schema:
        type: string
      example: Bearer USlfM8dilzKZPcuGGP3BfVLd7Snk
    clientIdParam:
      name: x-fapi-financial-id
      in: header
      description: Required. Provide 8 digit integer client id
      required: true
      style: simple
      explode: false
      schema:
        type: string
      example: "12345678"
  headers:
    interactionId:
      description: unique transaction ID created for each request for tracking purposes
      style: simple
      explode: false
      schema:
        type: string
        example: 95ad42fb-afd1-2121-b794-3ed29342ks42
  securitySchemes:
    BearerAuth:
      type: http
      description: Enter 'Bearer ' followed by the access token.
      scheme: bearer
